credentials:
  usernames:
         GF:
      email: gianfranco.fa@gmail.com
      name: Gianfranco
      password: '123' # To be replaced with hashed password
    
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - gianfranco.fa@gmail.com
